#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload example &
    bspc monitor $m -d 1 2 3 4 5 6 7 8 9
done

xdotool mousemove 20 20
# xdotool mousemove 960 540
xdotool mousemove 2880 540

bspc config border_width         6
bspc config window_gap          12

# bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc config normal_border_color "#86b3bd"
bspc config focused_border_color "#bb3d43"

xsetroot -cursor_name left_ptr

~/.config/polybar/launch.sh
picom --config ~/.config/picom.conf --backend glx 
